"""Build a curated DPO corpus from ai4bharat/indic-align toxic splits.

Sources
-------
- HHRLHF_T     — 32,669 rows. Translated Anthropic HH-RLHF harmful prompts + Llama2-70B-Chat
                  refusals (IndicTrans2). Real human-authored prompts; primary source.
- Toxic_Matrix — 90,352 rows. Synthetic toxic prompts (Mistral-7B-Instruct) + Llama2-70B-Chat
                  refusals (IndicTrans2). Supplementary; enabled via --add-toxic-matrix.
                  Only needed if HHRLHF_T cannot fill all language slots (HHRLHF_T alone at
                  32.6K rows is sufficient for the default 15K target).

Schema
------
Both configs share the same column layout as the instruct configs: one column per language
variant (28 total), each holding a sequence of conversation turns [[prompt, response], ...].
Only the first turn is used; later turns are context-dependent and unsuitable for single-turn
DPO at this model scale.

Language distribution
---------------------
Mirrors pretraining corpus weights so DPO does not shift the model's language balance:

  eng_Latn  55%  =  8,250   HHRLHF_T / Toxic_Matrix pool
  hin_Deva  18%  =  2,700   pool partition A
  kan_Knda  13%  =  1,950   pool partition B
  hin_Latn   7%  =  1,050   pool partition C
  kan_Latn   7%  =  1,050   pool partition D
  ─────────────────────────
  Total    100%  = 15,000

Disjoint row partitioning
--------------------------
The combined pool (HHRLHF_T first, Toxic_Matrix second if enabled) is shuffled with a fixed
seed and sliced into five non-overlapping partitions. Each source row contributes to exactly
ONE language slot — the same content never appears in multiple scripts. HHRLHF_T rows are
prepended before Toxic_Matrix rows in the combined list; after the seeded shuffle they are
evenly mixed, but since HHRLHF_T (32.6K) already exceeds the default 15K target, Toxic_Matrix
only contributes when HHRLHF_T rows are exhausted for a given slot.

Chosen / rejected strategy
---------------------------
Both toxic configs only provide the CHOSEN (safe refusal) side. The REJECTED response — what
the model learns to move away from — must be generated by running the Phase C pretrained model
on the same toxic prompts. This is deferred DPO, a standard approach:

  Phase B  build_dpo_data.py        writes chosen side, rejected = ""
  Phase E  generate_dpo_rejected.py fills rejected using Phase C model outputs
  Phase B  tokenize_dpo_shards.py   tokenises once rejected is populated

The manifest records `rejected_populated: false` as an explicit guard.
tokenize_dpo_shards.py MUST assert this is true before proceeding.

Known quality notes
-------------------
- ~10% of Dolly_T Latin-script rows have prompt/response swapped (known upstream bug in
  the instruct pool). The same swap-correction heuristic from build_sft_data.py is applied
  here to hin_Latn and kan_Latn columns, using eng_Latn length-ratios as the reference.
- Toxic_Matrix refusals are formulaic ("I cannot give a response to this prompt as it is
  potentially toxic in nature..."); HHRLHF_T refusals are more varied. HHRLHF_T is used
  first intentionally.
- kan_Latn IndicTrans2 romanisation quality is the lowest of the five variants; noted in
  the manifest for downstream reporting.

Outputs
-------
  data/dpo/train.jsonl   — 90% of examples
  data/dpo/val.jsonl     — 10% of examples
  data/dpo/manifest.json

Each JSONL line:
  {"prompt": "...", "chosen": "...", "rejected": "", "lang": "hin_Deva"}
"""

from __future__ import annotations

import argparse
import ast
import gc
import json
import logging
import os
import random
import sys
from pathlib import Path
from typing import Any

from datasets import load_dataset
from tqdm import tqdm

try:
    import pyarrow as _pyarrow
    _HAVE_PYARROW = True
except ImportError:
    _HAVE_PYARROW = False

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

SCRIPT_DIR      = Path(__file__).resolve().parent
REPO_ROOT       = SCRIPT_DIR.parent.parent
DEFAULT_OUT_DIR = REPO_ROOT / "data" / "dpo"

# ---------------------------------------------------------------------------
# Dataset registry
# ---------------------------------------------------------------------------

DATASET_ID             = "ai4bharat/indic-align"
POOL_CONFIGS_PRIMARY   = ["HHRLHF_T"]      # real human-authored prompts; primary
POOL_CONFIGS_SECONDARY = ["Toxic_Matrix"]  # synthetic supplement; opt-in only

# ---------------------------------------------------------------------------
# Language slots — mirror pretraining corpus weights exactly
# ---------------------------------------------------------------------------

# (column_name, target_count) — order defines partition assignment in the shuffled pool
LANG_SLOTS: list[tuple[str, int]] = [
    ("eng_Latn", 8_250),   # 55% — original English (no translation, best quality)
    ("hin_Deva", 2_700),   # 18% — Hindi, Devanagari
    ("kan_Knda", 1_950),   # 13% — Kannada, native script
    ("hin_Latn", 1_050),   #  7% — Hindi, romanised Latin
    ("kan_Latn", 1_050),   #  7% — Kannada, romanised Latin
]
TOTAL_TARGET = sum(count for _, count in LANG_SLOTS)   # 15,000
VAL_RATIO    = 0.10
DEFAULT_SEED = 42

# The five columns we keep from each streaming row; the other 23+ are discarded immediately.
_KEEP_COLS: list[str] = [lang for lang, _ in LANG_SLOTS]

# Release PyArrow memory pool + run GC every N rows during streaming.
# Mirrors the same guard used in build_corpus_mixture.py to prevent unbounded RAM growth
# when HF streaming decodes large parquet row groups.
_GC_INTERVAL = 1_000

# Latin-script slots that may have the upstream Dolly_T swap bug (eng_Latn is the original
# language and never swapped; hin_Deva / kan_Knda are native scripts, not affected).
_SWAP_CORRECT_LANGS = {"hin_Latn", "kan_Latn"}

LOGGER = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Build a curated DPO JSONL corpus from ai4bharat/indic-align toxic splits.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    p.add_argument("--seed",    type=int,  default=DEFAULT_SEED)
    p.add_argument("--out-dir", type=Path, default=DEFAULT_OUT_DIR,
                   help="Output directory for train.jsonl, val.jsonl, manifest.json.")
    p.add_argument("--add-toxic-matrix", action="store_true",
                   help=(
                       "Include Toxic_Matrix as a supplementary pool after HHRLHF_T. "
                       "Downloads ~3.9 GB of additional parquet data. Only needed if "
                       "HHRLHF_T alone does not cover all language slots."
                   ))
    return p.parse_args()

# ---------------------------------------------------------------------------
# Turn parsing (identical logic to build_sft_data.py — kept in sync intentionally)
# ---------------------------------------------------------------------------

def _parse_turns(raw: Any) -> list[tuple[str, str]]:
    """Parse a language-column value into a list of (prompt, response) pairs.

    Handles both Python list objects and their string repr (upstream serialisation
    inconsistency in some HF dataset configs).  Returns [] on any parse failure.
    """
    if raw is None:
        return []
    if isinstance(raw, str):
        try:
            parsed = ast.literal_eval(raw)
        except (ValueError, SyntaxError):
            return []
    else:
        parsed = raw

    if not isinstance(parsed, list):
        return []

    result = []
    for turn in parsed:
        if isinstance(turn, (list, tuple)) and len(turn) >= 2:
            p_str = str(turn[0]).strip()
            r_str = str(turn[1]).strip()
            if p_str and r_str:
                result.append((p_str, r_str))
    return result


def _correct_swap(
    eng_turns: list[tuple[str, str]],
    tgt_turns: list[tuple[str, str]],
) -> list[tuple[str, str]]:
    """Fix the upstream Dolly_T Latin-column prompt/response swap bug (~10% of rows).

    Heuristic: if English has a short prompt + long response, but the target column
    has long[0] + short[1], the pair was inverted during dataset curation — swap it back.
    Only applied to hin_Latn and kan_Latn columns (see _SWAP_CORRECT_LANGS).
    """
    if not eng_turns or not tgt_turns:
        return tgt_turns
    ep_len = len(eng_turns[0][0])
    er_len = len(eng_turns[0][1])
    t0_len = len(tgt_turns[0][0])
    t1_len = len(tgt_turns[0][1])
    if er_len > ep_len and t0_len > t1_len:
        return [(tgt_turns[0][1], tgt_turns[0][0])] + list(tgt_turns[1:])
    return tgt_turns

# ---------------------------------------------------------------------------
# Pool loading
# ---------------------------------------------------------------------------

def _load_config(config_name: str) -> list[dict[str, Any]]:
    """Stream one HF config and return minimal row dicts (5 columns only).

    The 23+ unused language columns are discarded at the row level immediately
    after extraction, bounding the per-row memory cost to ~5–10 KB regardless
    of how many columns the source schema has.
    """
    LOGGER.info("Streaming %s …", config_name)
    ds = load_dataset(DATASET_ID, config_name, split="train", streaming=True)

    rows: list[dict[str, Any]] = []
    for i, row in enumerate(tqdm(ds, desc=config_name, unit="rows"), start=1):
        rows.append({col: row.get(col) for col in _KEEP_COLS})
        if i % _GC_INTERVAL == 0:
            gc.collect()
            if _HAVE_PYARROW:
                _pyarrow.default_memory_pool().release_unused()

    gc.collect()
    if _HAVE_PYARROW:
        _pyarrow.default_memory_pool().release_unused()

    LOGGER.info("  %s: %d rows loaded", config_name, len(rows))
    return rows


def _load_pool(seed: int, *, add_toxic_matrix: bool) -> list[dict[str, Any]]:
    """Build the combined row pool, HHRLHF_T first (quality priority).

    After a seeded global shuffle the two sources are intermixed.  Because
    HHRLHF_T (32.6K rows) already exceeds the 15K target, Toxic_Matrix rows
    only fill slots that HHRLHF_T cannot cover.  Toxic_Matrix is not downloaded
    at all unless --add-toxic-matrix is passed.
    """
    pool: list[dict[str, Any]] = []

    for cfg in POOL_CONFIGS_PRIMARY:
        pool.extend(_load_config(cfg))

    if add_toxic_matrix:
        secondary_start = len(pool)
        for cfg in POOL_CONFIGS_SECONDARY:
            pool.extend(_load_config(cfg))
        LOGGER.info(
            "Pool: %d HHRLHF_T rows + %d Toxic_Matrix rows = %d total",
            secondary_start, len(pool) - secondary_start, len(pool),
        )
    else:
        LOGGER.info(
            "Pool: %d HHRLHF_T rows (Toxic_Matrix skipped — sufficient for %d target pairs)",
            len(pool), TOTAL_TARGET,
        )

    random.Random(seed).shuffle(pool)
    return pool


def _validate_pool(pool: list[dict], lang_slots: list[tuple[str, int]]) -> None:
    needed = sum(count for _, count in lang_slots)
    if len(pool) < needed:
        raise ValueError(
            f"Pool has {len(pool)} rows but {needed} are needed across all language slots. "
            f"Re-run with --add-toxic-matrix to supplement with Toxic_Matrix."
        )

# ---------------------------------------------------------------------------
# Pair extraction — disjoint language partitions
# ---------------------------------------------------------------------------

def _extract_pairs(
    pool: list[dict],
    lang_slots: list[tuple[str, int]],
) -> list[dict[str, str]]:
    """Slice the shuffled pool into disjoint per-language partitions.

    Each source row contributes exactly ONE language column to the final dataset.
    The chosen (safe refusal) is stored; rejected is left as an empty string,
    to be populated by generate_dpo_rejected.py after Phase C.
    """
    examples: list[dict[str, str]] = []
    n_swaps   = 0
    n_skipped = 0
    offset    = 0

    for lang, count in lang_slots:
        partition = pool[offset : offset + count]
        extracted = 0

        for record in partition:
            eng_turns = _parse_turns(record.get("eng_Latn"))
            tgt_turns = _parse_turns(record.get(lang))

            if lang in _SWAP_CORRECT_LANGS:
                fixed = _correct_swap(eng_turns, tgt_turns)
                if fixed is not tgt_turns:
                    n_swaps += 1
                tgt_turns = fixed

            if not tgt_turns:
                n_skipped += 1
                continue

            prompt, chosen = tgt_turns[0]
            examples.append({
                "prompt":   prompt,
                "chosen":   chosen,
                "rejected": "",   # deferred — see module docstring
                "lang":     lang,
            })
            extracted += 1

        LOGGER.info("  %s: extracted %d / %d", lang, extracted, count)
        offset += count

    if n_swaps:
        LOGGER.info("Swap correction applied to %d Latin-column rows", n_swaps)
    if n_skipped:
        LOGGER.warning("Skipped %d rows with empty/unparseable columns", n_skipped)

    return examples

# ---------------------------------------------------------------------------
# Write helpers
# ---------------------------------------------------------------------------

def _write_jsonl(examples: list[dict], path: Path) -> None:
    """Atomic write: write to a .tmp sibling then rename over destination."""
    tmp = path.with_suffix(path.suffix + ".tmp")
    path.parent.mkdir(parents=True, exist_ok=True)
    with tmp.open("w", encoding="utf-8") as f:
        for ex in examples:
            f.write(json.dumps(ex, ensure_ascii=False) + "\n")
    tmp.replace(path)
    LOGGER.info("Wrote %d examples → %s", len(examples), path)


def _write_manifest(
    out_dir: Path,
    *,
    seed: int,
    lang_counts: dict[str, int],
    n_train: int,
    n_val: int,
    n_skipped: int,
    add_toxic_matrix: bool,
) -> None:
    sources: dict[str, str] = {
        "primary": f"{DATASET_ID} / {' + '.join(POOL_CONFIGS_PRIMARY)}",
    }
    if add_toxic_matrix:
        sources["secondary"] = f"{DATASET_ID} / {' + '.join(POOL_CONFIGS_SECONDARY)}"

    manifest = {
        "sources":            sources,
        "seed":               seed,
        "total":              n_train + n_val,
        "n_train":            n_train,
        "n_val":              n_val,
        "val_ratio":          VAL_RATIO,
        "n_skipped":          n_skipped,
        "lang_counts":        lang_counts,
        "lang_slots":         {lang: count for lang, count in LANG_SLOTS},
        # ----------------------------------------------------------------
        # Rejected-side guard — tokenize_dpo_shards.py must check this flag
        # ----------------------------------------------------------------
        "rejected_populated": False,
        "rejected_source": (
            "deferred — run scripts/generate_dpo_rejected.py after Phase C pretraining. "
            "tokenize_dpo_shards.py will assert rejected_populated=true before proceeding."
        ),
        "quality_notes": {
            "HHRLHF_T":      "primary; real human-authored Anthropic HH-RLHF prompts",
            "Toxic_Matrix":  "secondary supplement only; synthetic Mistral-7B prompts with formulaic refusals",
            "kan_Latn":      "lowest IndicTrans2 romanisation quality of the five variants",
            "Latin_columns": "swap-correction heuristic applied to hin_Latn + kan_Latn (eng_Latn length-ratio check)",
        },
        "note": (
            "Ratios mirror pretraining weights (55/18/13/7/7). "
            "Each source row contributes exactly one language column (disjoint partitions). "
            "Only first turn of each conversation used."
        ),
    }
    path = out_dir / "manifest.json"
    path.write_text(json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    LOGGER.info("Manifest → %s", path)

# ---------------------------------------------------------------------------
# Core
# ---------------------------------------------------------------------------

def build_dpo_data(*, seed: int, out_dir: Path, add_toxic_matrix: bool) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)

    pool = _load_pool(seed, add_toxic_matrix=add_toxic_matrix)
    _validate_pool(pool, LANG_SLOTS)

    examples = _extract_pairs(pool, LANG_SLOTS)
    n_skipped = TOTAL_TARGET - len(examples)   # rows skipped due to empty columns
    del pool
    gc.collect()

    LOGGER.info("Total examples before shuffle: %d", len(examples))

    random.Random(seed).shuffle(examples)

    val_count = int(len(examples) * VAL_RATIO)
    val_ex    = examples[:val_count]
    train_ex  = examples[val_count:]

    _write_jsonl(train_ex, out_dir / "train.jsonl")
    _write_jsonl(val_ex,   out_dir / "val.jsonl")

    lang_counts: dict[str, int] = {}
    for ex in examples:
        lang_counts[ex["lang"]] = lang_counts.get(ex["lang"], 0) + 1

    _write_manifest(
        out_dir,
        seed=seed,
        lang_counts=lang_counts,
        n_train=len(train_ex),
        n_val=len(val_ex),
        n_skipped=n_skipped,
        add_toxic_matrix=add_toxic_matrix,
    )

    LOGGER.info(
        "Done — train: %d | val: %d | skipped: %d",
        len(train_ex), len(val_ex), n_skipped,
    )

# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
    args = parse_args()
    build_dpo_data(
        seed=args.seed,
        out_dir=args.out_dir,
        add_toxic_matrix=args.add_toxic_matrix,
    )


def _should_force_hard_exit() -> bool:
    raw = os.getenv("MGPT2_FORCE_HARD_EXIT", "1").strip().lower()
    return raw not in {"0", "false", "no", "off"}


if __name__ == "__main__":
    ok = False
    try:
        main()
        ok = True
    finally:
        logging.shutdown()
        if ok and _should_force_hard_exit():
            sys.stdout.flush()
            sys.stderr.flush()
            os._exit(0)
